### PR TITLE
Update readme.md file

### PR DESCRIPTION
**Pull request by 2lazy2debug**
Update file with a paragraph about creating a new object from scratch.

### CODE REVIEW

**Comment by 2lazy2debug** [comment]
Hey @Rantanen , thanks for your review and I guess it's better to work out the example like you do. Indeed I was doing working something out for my company use and didn't really take the time to think about the fact that the example should be very generic (although I took 20 seconds to comment what the properties and objects were referring to!) 

Let me change that to spare @CraigHawker some time

**Comment by CraigHawker** [comment]
Thank you for the contribution!

I agree with @Rantanen.  Would it be possible for you to make these three changes and then re-submit?

- Should use the object type of 0 (zero), as this is a default object type in all vaults.
- Should use the class ID of 0 (zero), as this is a default document class in all vaults.
- Should additionally pass property 22 (twenty-two), which is a boolean property to state whether or not the object is a single-file-document (true) or not (false).  It can be false in this instance as it does not then require a file.

Regards,

Craig.

**Comment by 2lazy2debug** [comment]
Dear @CraigHawker and @Rantanen , 
I quickly did the required changes. 
As English is not my native language, I let you check whether you might want to rephrase the comments. 

Kind Regards

Manuel

**Comment by CraigHawker** [comment]
> Dear @CraigHawker and @Rantanen ,
> I quickly did the required changes.
> As English is not my native language, I let you check whether you might want to rephrase the comments.
> 
> Kind Regards
> 
> Manuel

It's a great addition, Manuel, thank you.  I gladly accept any updates to the library (including documentation), so making a couple of small changes to the English to help you are no problem at all.  The changes are merged and live!

Thanks again.

Craig.

**Comment by 2lazy2debug** [comment]
Dear Craig, 

Always a pleasure to help. I'll see if there's something else that could be a useful addition, I will. 

Best Regards,

Manuel.

**Pull request merged**
